### ISSUE TITLE
TypeError: ONNX node of type Slice is not supported.

### ISSUE THREAD

**Issue by look-recognize** [YukiNagato/onnx2caffe#18]
Hi, the slice layer is not supported?

**Comment by YukiNagato** [comment]
Hi, i add slice support in branch "feat/slice" just now, could you try this branch and see if it work?

**Comment by look-recognize** [comment]
OK. Thanks

**Comment by coolzhangfeng** [comment]
Is this slice a split in onnx, see the code only supports two outputs?
