### ISSUE TITLE
MobileNetV2.onnx转换失败

### ISSUE THREAD

**Issue by gtwell** [YukiNagato/onnx2caffe#38]
```
F0619 15:41:18.124826 21734 cudnn_conv_layer.cpp:53] 
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by gtwell** [comment]
自问自答一下吧。
这个问题主要是由于MobileNet depthwise层引发的，在caffe使用depthwise层prototxt中需要添加`engine: CAFFE`，否则会报cudnn错误。在转换模型时onnx2caffe中没有添加`engine: CAFFE`，需要自己将所有group convolution添加该参数。举个例子
```
layer {
  name: "362"
  type: "Convolution"
  bottom: "361"
  top: "362"
  convolution_param {
    num_output: 32
    bias_term: false
    group: 32
    pad_h: 1
    pad_w: 1
    kernel_h: 3
    kernel_w: 3
    stride_h: 1
    stride_w: 1
    dilation: 1
    engine: CAFFE
  }
```

**Comment by ruabuliuqiu** [comment]
重新修改caffe中的Makefile.conf，取消掉cudnn编译，载编译一次caffe，再执行就可以了。这种方法简单

**Comment by qiuhaining** [comment]
> 自问自答一下吧。
> 这个问题主要是由于MobileNet depthwise层引发的，在caffe使用depthwise层prototxt中需要添加`engine: CAFFE`，否则会报cudnn错误。在转换模型时onnx2caffe中没有添加`engine: CAFFE`，需要自己将所有group convolution添加该参数。举个例子
> 
> ```
> layer {
>   name: "362"
>   type: "Convolution"
>   bottom: "361"
>   top: "362"
>   convolution_param {
>     num_output: 32
>     bias_term: false
>     group: 32
>     pad_h: 1
>     pad_w: 1
>     kernel_h: 3
>     kernel_w: 3
>     stride_h: 1
>     stride_w: 1
>     dilation: 1
>     engine: CAFFE
>   }
> ```
你好，我这边实验发现将常规卷积改成深度可分离卷积之后虽然参数量和FLOPs减少了，但在GPU上的inference速度降低了，且指标也变差！为什么还有这么多人在用mobilenet和shufflenet？

**Comment by gtwell** [comment]
> > 自问自答一下吧。
> > 这个问题主要是由于MobileNet depthwise层引发的，在caffe使用depthwise层prototxt中需要添加`engine: CAFFE`，否则会报cudnn错误。在转换模型时onnx2caffe中没有添加`engine: CAFFE`，需要自己将所有group convolution添加该参数。举个例子
> > ```
> > layer {
> >   name: "362"
> >   type: "Convolution"
> >   bottom: "361"
> >   top: "362"
> >   convolution_param {
> >     num_output: 32
> >     bias_term: false
> >     group: 32
> >     pad_h: 1
> >     pad_w: 1
> >     kernel_h: 3
> >     kernel_w: 3
> >     stride_h: 1
> >     stride_w: 1
> >     dilation: 1
> >     engine: CAFFE
> >   }
> > ```
> 
> 你好，我这边实验发现将常规卷积改成深度可分离卷积之后虽然参数量和FLOPs减少了，但在GPU上的inference速度降低了，且指标也变差！为什么还有这么多人在用mobilenet和shufflenet？

我这边速度性能会变差，但是精度还是一样的，gpu上infer因为caffe没有专门对组卷积进行gpu优化，这里`engine：CAFFE`的意思差不多这个层在cpu上运算了，这么多人用mobilenet原因是移动端一般都会专门对组卷积优化例如ncnn这样的，又或者在cpu上跑，cpu上速度还是很明显的，这时候速度就会起来了。

**Comment by qiuhaining** [comment]
> > > 自问自答一下吧。
> > > 这个问题主要是由于MobileNet depthwise层引发的，在caffe使用depthwise层prototxt中需要添加`engine: CAFFE`，否则会报cudnn错误。在转换模型时onnx2caffe中没有添加`engine: CAFFE`，需要自己将所有group convolution添加该参数。举个例子
> > > ```
> > > layer {
> > >   name: "362"
> > >   type: "Convolution"
> > >   bottom: "361"
> > >   top: "362"
> > >   convolution_param {
> > >     num_output: 32
> > >     bias_term: false
> > >     group: 32
> > >     pad_h: 1
> > >     pad_w: 1
> > >     kernel_h: 3
> > >     kernel_w: 3
> > >     stride_h: 1
> > >     stride_w: 1
> > >     dilation: 1
> > >     engine: CAFFE
> > >   }
> > > ```
> > 
> > 
> > 你好，我这边实验发现将常规卷积改成深度可分离卷积之后虽然参数量和FLOPs减少了，但在GPU上的inference速度降低了，且指标也变差！为什么还有这么多人在用mobilenet和shufflenet？
> 
> 我这边速度性能会变差，但是精度还是一样的，gpu上infer因为caffe没有专门对组卷积进行gpu优化，这里`engine：CAFFE`的意思差不多这个层在cpu上运算了，这么多人用mobilenet原因是移动端一般都会专门对组卷积优化例如ncnn这样的，又或者在cpu上跑，cpu上速度还是很明显的，这时候速度就会起来了。

明白了，感谢！
